# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_sapmcelltemp.m -o python/pvl_sapmcelltemp.py
import numpy as np
import pandas as pd
import pvl_tools

def pvl_systemdef(**kwargs):
	Expect={'TMYmeta':'',
			'SurfTilt':('num','x>=0'),
			'SurfAz':('num'),
			'Albedo':('num','x>=0'),
			'SeriesModules':('default','default=1','num','x>=0'),
			'ParallelModules':('default','default=1','num','x>=0')}

	var=pvl_tools.Parse(kwargs,Expect)

	system={'SurfTilt':var.SurfTilt,
			'SurfAz':var.SurfAz,
			'Albedo':var.Albedo,
			'SeriesModules':var.SeriesModules,
			'ParallelModules':var.ParallelModules,
			'Lat':var.TMYmeta.latitude,
			'Long':var.TMYmeta.longitude,
			'TZ':var.TMYmeta.TZ,
			'name':var.TMYmeta.Name,
			'altitude':var.TMYmeta.altitude}
    
	return system

