# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_sapmcelltemp.m -o python/pvl_sapmcelltemp.py
import numpy as np
import pandas as pd
import pvl_tools

def pvl_globalinplane(**kwargs):
    Expect={'SurfTilt':('num','x>=0'),
        'SurfAz':('num','x>=-180','x<=180'),
        'AOI':('x>=0'),
        'DNI':('x>=0'),
        'In_Plane_SkyDiffuse':('x>=0'),
        'GR':('x>=0'),
        }

    var=pvl_tools.Parse(kwargs,Expect)

    Eb = var.DNI*np.cos(np.radians(var.AOI)) #Implies that AOI is relative to normal CHECK

    E = Eb + var.In_Plane_SkyDiffuse + var.GR
    Ediff = var.In_Plane_SkyDiffuse + var.GR


    
    return pd.DataFrame({'E':E,
                        'Eb':Eb,
                        'Ediff':Ediff})

