# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_sapmcelltemp.m -o python/pvl_sapmcelltemp.py
import numpy as np
import pandas as pd
import pvl_tools

def pvl_sapmcelltemp(**kwargs):
    Expect={'a':('optional','num'),
            'b':('optional','num'),
            'deltaT':('optional','num'), 
            'E':('x>=0'),
            'Wspd':('x>=0'),
            'DryBulb':('x>=0'),
            'modelt': ('default','default=Open_rack_cell_glassback')
            }
    
    var=pvl_tools.Parse(kwargs,Expect)

    TempModel={'Open_rack_cell_glassback':[-3.47, -.0594, 3],
                'Roof_mount_cell_glassback':[-2.98, -.0471, 1],
                'Open_rack_cell_polymerback': [-3.56, -.0750, 3],
                'Insulated_back_polumerback': [-2.81, -.0455, 0 ],
                'Open_rack_Polymer_thinfilm_steel':[-3.58, -.113, 3],
                '22X_Concentrator_tracker':[-3.23, -.130, 13]
            }
    try: 
        a=var.a
        b=var.b
        deltaT=var.deltaT
    except:
        a=TempModel[var.modelt][0]
        b=TempModel[var.modelt][1]
        deltaT=TempModel[var.modelt][2]

    E0=1000 # Reference irradiance

    Tmodule=var.E*((np.exp(a + b*var.Wspd))) + var.DryBulb

    Tcell=Tmodule + var.E / E0*(deltaT)
    
    return pd.DataFrame({'Tcell':Tcell,'Tmodule':Tmodule})
