# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_makelocationstruct.m -o python/pvl_makelocationstruct.py
import numpy as np
import pvl_tools as pvt
import pdb

def pvl_makelocationstruct(**kwargs):
    Expect={'latitude':('num','x>=-90','x<=90'),
            'longitude': ('num','x<=180','x>=-180'),
            'altitude':('num','default','default=100'),
            }
    Location=pvt.Parse(kwargs,Expect)
    

    return Location
