# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_leapyear.m -o python/pvl_leapyear.py

import numpy as np
import pvl_tools as pvt

def pvl_leapyear(**kwargs):
	Expect={'Year':('num','x>0')}
	v=pvt.Parse(kwargs,Expect)
	v.Year=np.floor(v.Year)
	LY=(((np.mod(v.Year,4) == 0) & (np.mod(v.Year,100) != 0)) | (np.mod(v.Year,400) == 0))
	
	return LY
