# Autogenerated with SMOP version 0.23
# /usr/local/bin/smop pvl_alt2pres.m -o python/pvl_alt2pres.

import numpy as np
import pvl_tools as pvt

def pvl_alt2pres(**kwargs):
    Expect={'altitude', 'num'}
    var=pvl_tools.Parse(kwargs,Expect)

    Press=100 * ((44331.514 - var.altitude) / 11880.516) ** (1 / 0.1902632)
    
    return Press
