name: Update Top Ranked Issues

on:
  schedule:
    # Runs every day at 00:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    # Run only if the repository is pvlib/pvlib-python
    if: ${{ github.repository == 'pvlib/pvlib-python' }}

    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # This ensures the repository code is available

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run update_top_ranking_issues.py
        run: |
          python ./scripts/update_top_ranking_issues.py
